security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: '$2y$13$oYDgEug.WFOjJJunlxFIIeOzNJIj9Pn15EKvl6KCM0r7qBB/rK/Ee' 
                        roles: 'ROLE_USER'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: in_memory 
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: '/'
            logout:
                path: app_logout
                target: "/"

    access_control:
        - { path: ^/wishlist, roles: ROLE_USER }
